import type { Club } from '@/types/club';

export const FALLBACK_CLUB_LOGO = {
  src: '/clubs/fallback-club.svg',
  alt: 'Club logo unavailable',
  width: 40,
  height: 40,
};

export const clubs: Club[] = [
  {
    id: 'manchester-city',
    name: 'Manchester City',
    shortName: 'Man City',
    slug: 'manchester-city',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/manchester-city.png',
    logo: {
      src: '/clubs/manchester-city.png',
      alt: 'Manchester City official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Manchester City', 'Man City', 'City'],
    country: 'England',
    city: 'Manchester',
    websiteUrl: 'https://www.mancity.com',
    description: 'Premier League champions based at the Etihad Stadium.',
  },
  {
    id: 'liverpool',
    name: 'Liverpool',
    shortName: 'Liverpool',
    slug: 'liverpool',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/liverpool.png',
    logo: {
      src: '/clubs/liverpool.png',
      alt: 'Liverpool FC official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Liverpool', 'LFC', 'The Reds'],
    country: 'England',
    city: 'Liverpool',
    websiteUrl: 'https://www.liverpoolfc.com',
    description: 'Premier League club based at Anfield.',
  },
  {
    id: 'real-madrid',
    name: 'Real Madrid',
    shortName: 'Real Madrid',
    slug: 'real-madrid',
    league: 'La Liga',
    leagueId: 'la-liga',
    crestUrl: '/clubs/real-madrid.png',
    logo: {
      src: '/clubs/real-madrid.png',
      alt: 'Real Madrid official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Real Madrid', 'Madrid', 'Los Blancos'],
    country: 'Spain',
    city: 'Madrid',
    websiteUrl: 'https://www.realmadrid.com',
    description: 'La Liga club based in Madrid.',
  },
  {
    id: 'chelsea',
    name: 'Chelsea',
    shortName: 'Chelsea',
    slug: 'chelsea',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/chelsea.png',
    logo: {
      src: '/clubs/chelsea.png',
      alt: 'Chelsea FC official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Chelsea', 'CFC', 'Blues'],
    country: 'England',
    city: 'London',
    websiteUrl: 'https://www.chelseafc.com',
    description: 'Premier League club based at Stamford Bridge.',
  },
  {
    id: 'manchester-united',
    name: 'Manchester United',
    shortName: 'Man United',
    slug: 'manchester-united',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/manchester-united.png',
    logo: {
      src: '/clubs/manchester-united.png',
      alt: 'Manchester United official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Manchester United', 'Man United', 'Man Utd', 'MUFC'],
    country: 'England',
    city: 'Manchester',
    websiteUrl: 'https://www.manutd.com',
    description: 'Premier League club based at Old Trafford.',
  },
  {
    id: 'arsenal',
    name: 'Arsenal',
    shortName: 'Arsenal',
    slug: 'arsenal',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/arsenal.png',
    logo: {
      src: '/clubs/arsenal.png',
      alt: 'Arsenal FC official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Arsenal', 'Gunners'],
    country: 'England',
    city: 'London',
    websiteUrl: 'https://www.arsenal.com',
    description: 'North London club with a large global fanbase.',
  },
  {
    id: 'tottenham-hotspur',
    name: 'Tottenham Hotspur',
    shortName: 'Spurs',
    slug: 'tottenham-hotspur',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/tottenham-hotspur.png',
    logo: {
      src: '/clubs/tottenham-hotspur.png',
      alt: 'Tottenham Hotspur official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Tottenham Hotspur', 'Tottenham', 'Spurs'],
    country: 'England',
    city: 'London',
    websiteUrl: 'https://www.tottenhamhotspur.com',
    description: 'Premier League club based in North London.',
  },
  {
    id: 'atletico-madrid',
    name: 'Atletico Madrid',
    shortName: 'Atlético',
    slug: 'atletico-madrid',
    league: 'La Liga',
    leagueId: 'la-liga',
    crestUrl: '/clubs/atletico-madrid.png',
    logo: {
      src: '/clubs/atletico-madrid.png',
      alt: 'Atletico Madrid official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Atletico Madrid', 'Atlético Madrid', 'Atletico', 'Atlético'],
    country: 'Spain',
    city: 'Madrid',
    websiteUrl: 'https://www.atleticodemadrid.com',
    description: 'La Liga club based in Madrid.',
  },
  {
    id: 'napoli',
    name: 'Napoli',
    shortName: 'Napoli',
    slug: 'napoli',
    league: 'Serie A',
    leagueId: 'serie-a',
    crestUrl: '/clubs/napoli.png',
    logo: {
      src: '/clubs/napoli.png',
      alt: 'SSC Napoli official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Napoli', 'SSC Napoli'],
    country: 'Italy',
    city: 'Naples',
    websiteUrl: 'https://sscnapoli.it',
    description: 'Serie A club based in Naples.',
  },
  {
    id: 'aston-villa',
    name: 'Aston Villa',
    shortName: 'Aston Villa',
    slug: 'aston-villa',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/aston-villa.png',
    logo: {
      src: '/clubs/aston-villa.png',
      alt: 'Aston Villa official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Aston Villa', 'Villa'],
    country: 'England',
    city: 'Birmingham',
    websiteUrl: 'https://www.avfc.co.uk',
    description: 'Premier League club based in Birmingham.',
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    shortName: 'Barcelona',
    slug: 'barcelona',
    league: 'La Liga',
    leagueId: 'la-liga',
    crestUrl: '/clubs/barcelona.png',
    logo: {
      src: '/clubs/barcelona.png',
      alt: 'FC Barcelona official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Barcelona', 'Barca', 'Barça'],
    country: 'Spain',
    city: 'Barcelona',
    websiteUrl: 'https://www.fcbarcelona.com',
    description: 'Historic Catalan club competing in La Liga.',
  },
  {
    id: 'inter',
    name: 'Inter',
    shortName: 'Inter',
    slug: 'inter',
    league: 'Serie A',
    leagueId: 'serie-a',
    crestUrl: '/clubs/inter.png',
    logo: {
      src: '/clubs/inter.png',
      alt: 'Inter Milan official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Inter', 'Inter Milan', 'Internazionale'],
    country: 'Italy',
    city: 'Milan',
    websiteUrl: 'https://www.inter.it',
    description: 'Serie A club from Milan.',
  },
  {
    id: 'bayern-munich',
    name: 'Bayern Munich',
    shortName: 'Bayern',
    slug: 'bayern-munich',
    league: 'Bundesliga',
    leagueId: 'bundesliga',
    crestUrl: '/clubs/bayern-munich.png',
    logo: {
      src: '/clubs/bayern-munich.png',
      alt: 'Bayern Munich official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Bayern', 'Bayern Munich', 'FC Bayern'],
    country: 'Germany',
    city: 'Munich',
    websiteUrl: 'https://fcbayern.com',
    description: 'Bundesliga powerhouse based in Munich.',
  },
  {
    id: 'psg',
    name: 'Paris Saint-Germain',
    shortName: 'PSG',
    slug: 'psg',
    league: 'Ligue 1',
    leagueId: 'ligue-1',
    crestUrl: '/clubs/psg.png',
    logo: {
      src: '/clubs/psg.png',
      alt: 'Paris Saint-Germain official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['PSG', 'Paris Saint-Germain'],
    country: 'France',
    city: 'Paris',
    websiteUrl: 'https://www.psg.fr',
    description: 'Ligue 1 club from Paris.',
  },
  {
    id: 'trabzonspor',
    name: 'Trabzonspor',
    shortName: 'Trabzonspor',
    slug: 'trabzonspor',
    league: 'Süper Lig',
    leagueId: 'super-lig',
    crestUrl: '/clubs/trabzonspor.png',
    logo: {
      src: '/clubs/trabzonspor.png',
      alt: 'Trabzonspor official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Trabzonspor', 'Trabzon'],
    country: 'Turkey',
    city: 'Trabzon',
    websiteUrl: 'https://www.trabzonspor.org.tr',
    description: 'Turkish Süper Lig club.',
  },
  {
    id: 'galatasaray',
    name: 'Galatasaray',
    shortName: 'Galatasaray',
    slug: 'galatasaray',
    league: 'Süper Lig',
    leagueId: 'super-lig',
    crestUrl: '/clubs/galatasaray.png',
    logo: {
      src: '/clubs/galatasaray.png',
      alt: 'Galatasaray official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Galatasaray', 'Cimbom'],
    country: 'Turkey',
    city: 'Istanbul',
    websiteUrl: 'https://www.galatasaray.org',
    description: 'Turkish Süper Lig club.',
  },
  {
    id: 'fenerbahce',
    name: 'Fenerbahce',
    shortName: 'Fenerbahce',
    slug: 'fenerbahce',
    league: 'Süper Lig',
    leagueId: 'super-lig',
    crestUrl: '/clubs/fenerbahce.png',
    logo: {
      src: '/clubs/fenerbahce.png',
      alt: 'Fenerbahce official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Fenerbahce', 'Fenerbahçe', 'Fener'],
    country: 'Turkey',
    city: 'Istanbul',
    websiteUrl: 'https://www.fenerbahce.org',
    description: 'Turkish Süper Lig club.',
  },
  {
    id: 'al-ittihad',
    name: 'Al-Ittihad',
    shortName: 'Al-Ittihad',
    slug: 'al-ittihad',
    league: 'Saudi Pro League',
    leagueId: 'saudi-pro-league',
    crestUrl: '/clubs/al-ittihad.png',
    logo: {
      src: '/clubs/al-ittihad.png',
      alt: 'Al-Ittihad official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Al-Ittihad', 'Ittihad'],
    country: 'Saudi Arabia',
    city: 'Jeddah',
    websiteUrl: 'https://ittihad.sa',
    description: 'Saudi Pro League club.',
  },
  {
    id: 'al-nassr',
    name: 'Al-Nassr',
    shortName: 'Al-Nassr',
    slug: 'al-nassr',
    league: 'Saudi Pro League',
    leagueId: 'saudi-pro-league',
    crestUrl: '/clubs/al-nassr.png',
    logo: {
      src: '/clubs/al-nassr.png',
      alt: 'Al-Nassr official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Al-Nassr', 'Al Nassr', 'Nassr'],
    country: 'Saudi Arabia',
    city: 'Riyadh',
    websiteUrl: 'https://alnassr.sa',
    description: 'Saudi Pro League club.',
  },
  {
    id: 'sporting-cp',
    name: 'Sporting CP',
    shortName: 'Sporting CP',
    slug: 'sporting-cp',
    league: 'Primeira Liga',
    leagueId: 'primeira-liga',
    crestUrl: '/clubs/sporting-cp.png',
    logo: {
      src: '/clubs/sporting-cp.png',
      alt: 'Sporting CP official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Sporting CP', 'Sporting Lisbon'],
    country: 'Portugal',
    city: 'Lisbon',
    websiteUrl: 'https://www.sporting.pt',
    description: 'Portuguese Primeira Liga club.',
  },
  {
    id: 'newcastle-united',
    name: 'Newcastle United',
    shortName: 'Newcastle',
    slug: 'newcastle-united',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/newcastle-united.png',
    logo: {
      src: '/clubs/newcastle-united.png',
      alt: 'Newcastle United official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Newcastle United', 'Newcastle', 'Magpies'],
    country: 'England',
    city: 'Newcastle',
    websiteUrl: 'https://www.nufc.co.uk',
    description: 'Premier League club based in Newcastle.',
  },
  {
    id: 'west-ham-united',
    name: 'West Ham United',
    shortName: 'West Ham',
    slug: 'west-ham-united',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/west-ham-united.png',
    logo: {
      src: '/clubs/west-ham-united.png',
      alt: 'West Ham United official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['West Ham United', 'West Ham', 'Hammers'],
    country: 'England',
    city: 'London',
    websiteUrl: 'https://www.whufc.com',
    description: 'Premier League club based in East London.',
  },
  {
    id: 'brighton',
    name: 'Brighton & Hove Albion',
    shortName: 'Brighton',
    slug: 'brighton',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/brighton.png',
    logo: {
      src: '/clubs/brighton.png',
      alt: 'Brighton official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Brighton', 'Brighton & Hove Albion', 'Seagulls'],
    country: 'England',
    city: 'Brighton',
    websiteUrl: 'https://www.brightonandhovealbion.com',
    description: 'Premier League club based in Brighton.',
  },
  {
    id: 'brentford',
    name: 'Brentford',
    shortName: 'Brentford',
    slug: 'brentford',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/brentford.png',
    logo: {
      src: '/clubs/brentford.png',
      alt: 'Brentford official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Brentford', 'Bees'],
    country: 'England',
    city: 'London',
    websiteUrl: 'https://www.brentfordfc.com',
    description: 'Premier League club based in West London.',
  },
  {
    id: 'crystal-palace',
    name: 'Crystal Palace',
    shortName: 'Palace',
    slug: 'crystal-palace',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/crystal-palace.png',
    logo: {
      src: '/clubs/crystal-palace.png',
      alt: 'Crystal Palace official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Crystal Palace', 'Palace', 'Eagles'],
    country: 'England',
    city: 'London',
    websiteUrl: 'https://www.cpfc.co.uk',
    description: 'Premier League club based in South London.',
  },
  {
    id: 'everton',
    name: 'Everton',
    shortName: 'Everton',
    slug: 'everton',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/everton.png',
    logo: {
      src: '/clubs/everton.png',
      alt: 'Everton official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Everton', 'Toffees'],
    country: 'England',
    city: 'Liverpool',
    websiteUrl: 'https://www.evertonfc.com',
    description: 'Premier League club based in Liverpool.',
  },
  {
    id: 'fulham',
    name: 'Fulham',
    shortName: 'Fulham',
    slug: 'fulham',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/fulham.png',
    logo: {
      src: '/clubs/fulham.png',
      alt: 'Fulham official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Fulham', 'Cottagers'],
    country: 'England',
    city: 'London',
    websiteUrl: 'https://www.fulhamfc.com',
    description: 'Premier League club based at Craven Cottage.',
  },
  {
    id: 'wolverhampton-wanderers',
    name: 'Wolverhampton Wanderers',
    shortName: 'Wolves',
    slug: 'wolverhampton-wanderers',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/wolverhampton-wanderers.png',
    logo: {
      src: '/clubs/wolverhampton-wanderers.png',
      alt: 'Wolves official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Wolverhampton Wanderers', 'Wolves', 'Wolverhampton'],
    country: 'England',
    city: 'Wolverhampton',
    websiteUrl: 'https://www.wolves.co.uk',
    description: 'Premier League club based in Wolverhampton.',
  },
  {
    id: 'bournemouth',
    name: 'Bournemouth',
    shortName: 'Bournemouth',
    slug: 'bournemouth',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/bournemouth.png',
    logo: {
      src: '/clubs/bournemouth.png',
      alt: 'Bournemouth official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Bournemouth', 'AFCB', 'Cherries'],
    country: 'England',
    city: 'Bournemouth',
    websiteUrl: 'https://www.afcb.co.uk',
    description: 'Premier League club based in Bournemouth.',
  },
  {
    id: 'nottingham-forest',
    name: 'Nottingham Forest',
    shortName: 'Forest',
    slug: 'nottingham-forest',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/nottingham-forest.png',
    logo: {
      src: '/clubs/nottingham-forest.png',
      alt: 'Nottingham Forest official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Nottingham Forest', 'Forest', 'NFFC'],
    country: 'England',
    city: 'Nottingham',
    websiteUrl: 'https://www.nottinghamforest.co.uk',
    description: 'Premier League club based in Nottingham.',
  },
  {
    id: 'southampton',
    name: 'Southampton',
    shortName: 'Southampton',
    slug: 'southampton',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/southampton.png',
    logo: {
      src: '/clubs/southampton.png',
      alt: 'Southampton official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Southampton', 'Saints'],
    country: 'England',
    city: 'Southampton',
    websiteUrl: 'https://www.southamptonfc.com',
    description: 'Premier League club based in Southampton.',
  },
  {
    id: 'juventus',
    name: 'Juventus',
    shortName: 'Juventus',
    slug: 'juventus',
    league: 'Serie A',
    leagueId: 'serie-a',
    crestUrl: '/clubs/juventus.png',
    logo: {
      src: '/clubs/juventus.png',
      alt: 'Juventus official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Juventus', 'Juve'],
    country: 'Italy',
    city: 'Turin',
    websiteUrl: 'https://www.juventus.com',
    description: 'Serie A club from Turin.',
  },
  {
    id: 'ac-milan',
    name: 'AC Milan',
    shortName: 'Milan',
    slug: 'ac-milan',
    league: 'Serie A',
    leagueId: 'serie-a',
    crestUrl: '/clubs/ac-milan.png',
    logo: {
      src: '/clubs/ac-milan.png',
      alt: 'AC Milan official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['AC Milan', 'Milan', 'Rossoneri'],
    country: 'Italy',
    city: 'Milan',
    websiteUrl: 'https://www.acmilan.com',
    description: 'Serie A club from Milan.',
  },
  {
    id: 'roma',
    name: 'Roma',
    shortName: 'Roma',
    slug: 'roma',
    league: 'Serie A',
    leagueId: 'serie-a',
    crestUrl: '/clubs/roma.png',
    logo: {
      src: '/clubs/roma.png',
      alt: 'AS Roma official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Roma', 'AS Roma'],
    country: 'Italy',
    city: 'Rome',
    websiteUrl: 'https://www.asroma.com',
    description: 'Serie A club from Rome.',
  },
  {
    id: 'borussia-dortmund',
    name: 'Borussia Dortmund',
    shortName: 'Dortmund',
    slug: 'borussia-dortmund',
    league: 'Bundesliga',
    leagueId: 'bundesliga',
    crestUrl: '/clubs/borussia-dortmund.png',
    logo: {
      src: '/clubs/borussia-dortmund.png',
      alt: 'Borussia Dortmund official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Borussia Dortmund', 'Dortmund', 'BVB'],
    country: 'Germany',
    city: 'Dortmund',
    websiteUrl: 'https://www.bvb.de',
    description: 'Bundesliga powerhouse based in Dortmund.',
  },
  {
    id: 'porto',
    name: 'Porto',
    shortName: 'Porto',
    slug: 'porto',
    league: 'Primeira Liga',
    leagueId: 'primeira-liga',
    crestUrl: '/clubs/porto.png',
    logo: {
      src: '/clubs/porto.png',
      alt: 'FC Porto official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Porto', 'FC Porto'],
    country: 'Portugal',
    city: 'Porto',
    websiteUrl: 'https://www.fcporto.pt',
    description: 'Portuguese Primeira Liga club.',
  },
  {
    id: 'benfica',
    name: 'Benfica',
    shortName: 'Benfica',
    slug: 'benfica',
    league: 'Primeira Liga',
    leagueId: 'primeira-liga',
    crestUrl: '/clubs/benfica.png',
    logo: {
      src: '/clubs/benfica.png',
      alt: 'SL Benfica official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Benfica', 'SL Benfica'],
    country: 'Portugal',
    city: 'Lisbon',
    websiteUrl: 'https://www.slbenfica.pt',
    description: 'Portuguese Primeira Liga club.',
  },
  {
    id: 'leeds-united',
    name: 'Leeds United',
    shortName: 'Leeds',
    slug: 'leeds-united',
    league: 'Premier League',
    leagueId: 'premier-league',
    crestUrl: '/clubs/leeds-united.png',
    logo: {
      src: '/clubs/leeds-united.png',
      alt: 'Leeds United official crest logo',
      width: 40,
      height: 40,
    },
    aliases: ['Leeds United', 'Leeds', 'LUFC'],
    country: 'England',
    city: 'Leeds',
    websiteUrl: 'https://www.leedsunited.com',
    description: 'English football club based at Elland Road.',
  },
];

export const popularClubIds = ['manchester-city', 'real-madrid', 'liverpool', 'manchester-united', 'arsenal', 'chelsea', 'tottenham-hotspur'];

export function getClubById(id: string): Club | null {
  return clubs.find((club) => club.id === id) ?? null;
}

export function getClubBySlug(slug: string): Club | null {
  return clubs.find((club) => club.slug === slug) ?? null;
}