import type { Club } from '@/types/club';

export const clubs: Club[] = [
  {
    id: 'manchester-city',
    name: 'Manchester City',
    slug: 'manchester-city',
    league: 'Premier League',
    crestUrl: null,
    aliases: ['Manchester City', 'Man City', 'City'],
    country: 'England',
    city: 'Manchester',
    websiteUrl: 'https://www.mancity.com',
    description: 'Premier League champions based at the Etihad Stadium.',
  },
  {
    id: 'liverpool',
    name: 'Liverpool',
    slug: 'liverpool',
    league: 'Premier League',
    crestUrl: null,
    aliases: ['Liverpool', 'LFC', 'The Reds'],
    country: 'England',
    city: 'Liverpool',
    websiteUrl: 'https://www.liverpoolfc.com',
    description: 'Premier League club based at Anfield.',
  },
  {
    id: 'real-madrid',
    name: 'Real Madrid',
    slug: 'real-madrid',
    league: 'La Liga',
    crestUrl: null,
    aliases: ['Real Madrid', 'Madrid', 'Los Blancos'],
    country: 'Spain',
    city: 'Madrid',
    websiteUrl: 'https://www.realmadrid.com',
    description: 'La Liga club based in Madrid.',
  },
  {
    id: 'chelsea',
    name: 'Chelsea',
    slug: 'chelsea',
    league: 'Premier League',
    crestUrl: null,
    aliases: ['Chelsea', 'CFC', 'Blues'],
    country: 'England',
    city: 'London',
    websiteUrl: 'https://www.chelseafc.com',
    description: 'Premier League club based at Stamford Bridge.',
  },
  {
    id: 'manchester-united',
    name: 'Manchester United',
    slug: 'manchester-united',
    league: 'Premier League',
    crestUrl: null,
    aliases: ['Manchester United', 'Man United', 'Man Utd', 'MUFC'],
    country: 'England',
    city: 'Manchester',
    websiteUrl: 'https://www.manutd.com',
    description: 'Premier League club based at Old Trafford.',
  },
  {
    id: 'arsenal',
    name: 'Arsenal',
    slug: 'arsenal',
    league: 'Premier League',
    crestUrl: null,
    aliases: ['Arsenal', 'Gunners'],
    country: 'England',
    city: 'London',
    websiteUrl: 'https://www.arsenal.com',
    description: 'North London club with a large global fanbase.',
  },
  {
    id: 'aston-villa',
    name: 'Aston Villa',
    slug: 'aston-villa',
    league: 'Premier League',
    crestUrl: null,
    aliases: ['Aston Villa', 'Villa'],
    country: 'England',
    city: 'Birmingham',
    websiteUrl: 'https://www.avfc.co.uk',
    description: 'Premier League club based in Birmingham.',
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    slug: 'barcelona',
    league: 'La Liga',
    crestUrl: null,
    aliases: ['Barcelona', 'Barca', 'Barça'],
    country: 'Spain',
    city: 'Barcelona',
    websiteUrl: 'https://www.fcbarcelona.com',
    description: 'Historic Catalan club competing in La Liga.',
  },
  {
    id: 'inter',
    name: 'Inter',
    slug: 'inter',
    league: 'Serie A',
    crestUrl: null,
    aliases: ['Inter', 'Inter Milan', 'Internazionale'],
    country: 'Italy',
    city: 'Milan',
    websiteUrl: 'https://www.inter.it',
    description: 'Serie A club from Milan.',
  },
  {
    id: 'bayern-munich',
    name: 'Bayern Munich',
    slug: 'bayern-munich',
    league: 'Bundesliga',
    crestUrl: null,
    aliases: ['Bayern', 'Bayern Munich', 'FC Bayern'],
    country: 'Germany',
    city: 'Munich',
    websiteUrl: 'https://fcbayern.com',
    description: 'Bundesliga powerhouse based in Munich.',
  },
  {
    id: 'psg',
    name: 'Paris Saint-Germain',
    slug: 'psg',
    league: 'Ligue 1',
    crestUrl: null,
    aliases: ['PSG', 'Paris Saint-Germain'],
    country: 'France',
    city: 'Paris',
    websiteUrl: 'https://www.psg.fr',
    description: 'Ligue 1 club from Paris.',
  },
];

export const popularClubIds = ['manchester-city', 'real-madrid', 'liverpool', 'manchester-united', 'arsenal', 'chelsea'];

export function getClubById(id: string) {
  return clubs.find((club) => club.id === id) ?? null;
}

export function getClubBySlug(slug: string) {
  return clubs.find((club) => club.slug === slug) ?? null;
}